name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Move to the project folder
        run: cd ordo

      - name: Build with Maven
        run: mvn -B package --file ordo/pom.xml

      - name: Run tests
        run: mvn test --file ordo/pom.xml

      - name: Save Artifacts (JAR)
        uses: actions/upload-artifact@v4
        with:
          name: javafx-app
          path: ordo/target/*.jar

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
